import mongoose from 'mongoose';
import productModel from '../models/productModel.js';
import '../config/mongodb.js'; // Import MongoDB configuration

const sampleProducts = [
  {
    name: "Floral Print Kurti",
    description: "Beautiful floral print kurti with comfortable fit",
    price: 899,
    image: ["https://via.placeholder.com/300x400/FF6B6B/FFFFFF?text=Floral+Kurti"],
    gender: "women",
    category: "kurtis",
    subCategory: "casual",
    occasion: ["casual", "everyday"],
    type: ["kurti"],
    filterTags: ["floral", "printed", "cotton"],
    sizes: ["S", "M", "L", "XL"],
    hasSize: true,
    stock: { S: 15, M: 20, L: 18, XL: 12 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  }, 
  {
    name: "Embroidered Anarkali",
    description: "Elegant embroidered anarkali suit for special occasions",
    price: 1499,
    image: ["https://via.placeholder.com/300x400/4ECDC4/FFFFFF?text=Anarkali"],
    gender: "women",
    category: "anarkalis",
    subCategory: "formal",
    occasion: ["wedding", "party", "festival"],
    type: ["anarkali"],
    filterTags: ["embroidered", "formal", "luxury"],
    sizes: ["S", "M", "L"],
    hasSize: true,
    stock: { S: 8, M: 10, L: 7 },
    bestseller: false,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Cotton Daily Wear Kurti",
    description: "Comfortable cotton kurti for daily wear",
    price: 599,
    image: ["https://via.placeholder.com/300x400/45B7D1/FFFFFF?text=Cotton+Kurti"],
    gender: "women",
    category: "kurtis",
    subCategory: "casual",
    occasion: ["casual", "office"],
    type: ["kurti"],
    filterTags: ["cotton", "comfort", "daily"],
    sizes: ["S", "M", "L"],
    hasSize: true,
    stock: { S: 25, M: 30, L: 22 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Designer Party Wear",
    description: "Stylish designer wear for parties and events",
    price: 1999,
    image: ["https://via.placeholder.com/300x400/F7DC6F/FFFFFF?text=Designer+Wear"],
    gender: "women",
    category: "designer",
    subCategory: "party",
    occasion: ["party", "wedding"],
    type: ["designer"],
    filterTags: ["designer", "party", "luxury"],
    sizes: ["S", "M", "L"],
    hasSize: true,
    stock: { S: 6, M: 8, L: 5 },
    bestseller: false,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Printed Palazzo Set",
    description: "Trendy printed palazzo set with matching top",
    price: 1299,
    image: ["https://via.placeholder.com/300x400/BF40BF/FFFFFF?text=Palazzo+Set"],
    gender: "women",
    category: "sets",
    subCategory: "casual",
    occasion: ["casual", "outings"],
    type: ["palazzo"],
    filterTags: ["printed", "set", "comfort"],
    sizes: ["S", "M", "L"],
    hasSize: true,
    stock: { S: 12, M: 15, L: 10 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Silk Saree",
    description: "Elegant silk saree for traditional occasions",
    price: 2499,
    image: ["https://via.placeholder.com/300x400/FF7F50/FFFFFF?text=Silk+Saree"],
    gender: "women",
    category: "sarees",
    subCategory: "traditional",
    occasion: ["wedding", "festival"],
    type: ["saree"],
    filterTags: ["silk", "traditional", "elegant"],
    sizes: ["Free Size"],
    hasSize: false,
    stock: 18,
    bestseller: false,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Casual T-Shirt",
    description: "Comfortable casual t-shirt for everyday wear",
    price: 399,
    image: ["https://via.placeholder.com/300x400/6495ED/FFFFFF?text=T-Shirt"],
    gender: "men",
    category: "tshirts",
    subCategory: "casual",
    occasion: ["casual", "sports"],
    type: ["tshirt"],
    filterTags: ["casual", "cotton", "comfort"],
    sizes: ["S", "M", "L", "XL"],
    hasSize: true,
    stock: { S: 30, M: 35, L: 28, XL: 20 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Formal Shirt",
    description: "Classic formal shirt for office wear",
    price: 799,
    image: ["https://via.placeholder.com/300x400/808080/FFFFFF?text=Formal+Shirt"],
    gender: "men",
    category: "shirts",
    subCategory: "formal",
    occasion: ["office", "formal"],
    type: ["shirt"],
    filterTags: ["formal", "office", "classic"],
    sizes: ["S", "M", "L", "XL"],
    hasSize: true,
    stock: { S: 15, M: 18, L: 12, XL: 10 },
    bestseller: false,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Denim Jeans",
    description: "Stylish denim jeans for casual wear",
    price: 1299,
    image: ["https://via.placeholder.com/300x400/000080/FFFFFF?text=Denim+Jeans"],
    gender: "men",
    category: "jeans",
    subCategory: "casual",
    occasion: ["casual", "outings"],
    type: ["jeans"],
    filterTags: ["denim", "casual", "style"],
    sizes: ["28", "30", "32", "34"],
    hasSize: true,
    stock: { "28": 8, "30": 12, "32": 10, "34": 6 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Winter Jacket",
    description: "Warm winter jacket for cold weather",
    price: 1999,
    image: ["https://via.placeholder.com/300x400/A9A9A9/FFFFFF?text=Winter+Jacket"],
    gender: "men",
    category: "jackets",
    subCategory: "winter",
    occasion: ["winter", "casual"],
    type: ["jacket"],
    filterTags: ["winter", "warm", "comfort"],
    sizes: ["S", "M", "L", "XL"],
    hasSize: true,
    stock: { S: 10, M: 12, L: 8, XL: 5 },
    bestseller: false,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Kids T-Shirt",
    description: "Colorful t-shirt for kids",
    price: 299,
    image: ["https://via.placeholder.com/300x400/FF69B4/FFFFFF?text=Kids+T-Shirt"],
    gender: "kids",
    category: "kids",
    subCategory: "casual",
    occasion: ["casual", "school"],
    type: ["tshirt"],
    filterTags: ["kids", "colorful", "fun"],
    sizes: ["XS", "S", "M"],
    hasSize: true,
    stock: { XS: 20, S: 25, M: 18 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Kids Jeans",
    description: "Durable jeans for active kids",
    price: 599,
    image: ["https://via.placeholder.com/300x400/8A2BE2/FFFFFF?text=Kids+Jeans"],
    gender: "kids",
    category: "kids",
    subCategory: "casual",
    occasion: ["casual", "school"],
    type: ["jeans"],
    filterTags: ["kids", "durable", "active"],
    sizes: ["XS", "S", "M"],
    hasSize: true,
    stock: { XS: 15, S: 18, M: 12 },
    bestseller: false,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Baby Onesie",
    description: "Soft and comfortable onesie for babies",
    price: 399,
    image: ["https://via.placeholder.com/300x400/FFB6C1/FFFFFF?text=Baby+Onesie"],
    gender: "kids",
    category: "kids",
    subCategory: "baby",
    occasion: ["casual", "home"],
    type: ["onesie"],
    filterTags: ["baby", "soft", "comfort"],
    sizes: ["0-3M", "3-6M", "6-12M"],
    hasSize: true,
    stock: { "0-3M": 25, "3-6M": 20, "6-12M": 15 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Summer Dress",
    description: "Light and breezy summer dress",
    price: 899,
    image: ["https://via.placeholder.com/300x400/FFD700/FFFFFF?text=Summer+Dress"],
    gender: "women",
    category: "dresses",
    subCategory: "casual",
    occasion: ["casual", "beach"],
    type: ["dress"],
    filterTags: ["summer", "light", "breezy"],
    sizes: ["S", "M", "L"],
    hasSize: true,
    stock: { S: 18, M: 20, L: 15 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Evening Gown",
    description: "Elegant evening gown for special events",
    price: 2999,
    image: ["https://via.placeholder.com/300x400/9370DB/FFFFFF?text=Evening+Gown"],
    gender: "women",
    category: "gowns",
    subCategory: "formal",
    occasion: ["party", "wedding"],
    type: ["gown"],
    filterTags: ["elegant", "formal", "luxury"],
    sizes: ["S", "M", "L"],
    hasSize: true,
    stock: { S: 5, M: 6, L: 4 },
    bestseller: false,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Sports Shorts",
    description: "Comfortable sports shorts for active wear",
    price: 499,
    image: ["https://via.placeholder.com/300x400/32CD32/FFFFFF?text=Sports+Shorts"],
    gender: "men",
    category: "shorts",
    subCategory: "sports",
    occasion: ["sports", "casual"],
    type: ["shorts"],
    filterTags: ["sports", "active", "comfort"],
    sizes: ["S", "M", "L", "XL"],
    hasSize: true,
    stock: { S: 20, M: 25, L: 18, XL: 12 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Traditional Kurta",
    description: "Traditional kurta for men",
    price: 999,
    image: ["https://via.placeholder.com/300x400/CD853F/FFFFFF?text=Traditional+Kurta"],
    gender: "men",
    category: "kurtas",
    subCategory: "traditional",
    occasion: ["festival", "wedding"],
    type: ["kurta"],
    filterTags: ["traditional", "festive", "comfort"],
    sizes: ["S", "M", "L", "XL"],
    hasSize: true,
    stock: { S: 12, M: 15, L: 10, XL: 8 },
    bestseller: false,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Winter Sweater",
    description: "Warm winter sweater for cold days",
    price: 1299,
    image: ["https://via.placeholder.com/300x400/708090/FFFFFF?text=Winter+Sweater"],
    gender: "women",
    category: "sweaters",
    subCategory: "winter",
    occasion: ["winter", "casual"],
    type: ["sweater"],
    filterTags: ["winter", "warm", "comfort"],
    sizes: ["S", "M", "L"],
    hasSize: true,
    stock: { S: 15, M: 18, L: 12 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Leather Jacket",
    description: "Stylish leather jacket for fashion enthusiasts",
    price: 3499,
    image: ["https://via.placeholder.com/300x400/2F4F4F/FFFFFF?text=Leather+Jacket"],
    gender: "men",
    category: "jackets",
    subCategory: "fashion",
    occasion: ["casual", "party"],
    type: ["jacket"],
    filterTags: ["leather", "fashion", "style"],
    sizes: ["S", "M", "L", "XL"],
    hasSize: true,
    stock: { S: 6, M: 8, L: 5, XL: 3 },
    bestseller: false,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  },
  {
    name: "Beach Cover-up",
    description: "Light cover-up for beach days",
    price: 699,
    image: ["https://via.placeholder.com/300x400/87CEFA/FFFFFF?text=Beach+Cover-up"],
    gender: "women",
    category: "beachwear",
    subCategory: "casual",
    occasion: ["beach", "vacation"],
    type: ["coverup"],
    filterTags: ["beach", "light", "vacation"],
    sizes: ["S", "M", "L"],
    hasSize: true,
    stock: { S: 20, M: 22, L: 18 },
    bestseller: true,
    date: Date.now(),
    stockAlerts: [],
    filters: {}
  }
];

const addProducts = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/anmol_kurtis');
    
    console.log('Connected to MongoDB');
    
    // Clear existing products (optional)
    // await productModel.deleteMany({});
    // console.log('Cleared existing products');
    
    // Add sample products
    for (const productData of sampleProducts) {
      const product = new productModel(productData);
      await product.save();
      console.log(`Added product: ${productData.name}`);
    }
    
    console.log('All products added successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error adding products:', error);
    process.exit(1);
  }
};

addProducts();
